### ISSUE TITLE
TODO 2.10.2

### ISSUE THREAD

**Issue by xkeyC** [StarCitizenToolBox/app#1]
### Bugfix
- [x] 禁用系统文字缩放，解决某些设备UI溢出的问题。
- [x]  隐藏定时 RSS 刷新的错误提示。
- [x] 分流下载：增加一种快速恢复卡住的下载的方法。 
- [x] 性能优化：增加用户投稿的几个参数。增加自定义参数编辑框。
- [x] 开发版更新使用 cloudflare 分流
- [x] 汉化页面增加反馈按钮
- [x] RSI 汉化 忽略光谱 https://github.com/StarCitizenToolBox/StarCitizenBoxBrowserEx/issues/1

### New Feature
- [x] 增加一个工具站镜的加速像
- [x]  增加一个问卷调查

* 因 PartyRoom 相关开发时长超出预期，优先进行bug修复，咕咕至以后的版本  https://github.com/StarCitizenToolBox/app/issues/2

**Comment by xkeyC** [comment]
所有问题均已解决，推进正式版
